#!/bin/sh

set -a
set -e
set -u

. ./env-vars.sh

wget -P ${EPICS_INSTALL_DIR} ${EPICS_BASE_URL}

mkdir -p ${EPICS_INSTALL_DIR}/${EPICS_BASE_NAME}

tar -xvzf ${EPICS_INSTALL_DIR}/${EPICS_BASE_TAR_NAME}.tar.gz -C ${EPICS_INSTALL_DIR}/

rm ${EPICS_INSTALL_DIR}/${EPICS_BASE_TAR_NAME}.tar.gz

grep -r "IPPORT_USERRESERVED" ${EPICS_INSTALL_DIR}/${EPICS_BASE_NAME}/

make -C ${EPICS_INSTALL_DIR}/${EPICS_BASE_NAME}/

export EPICS_HOST_ARCH=linux-x86_64
export EPICS_CA_ADDR_LIST=10.0.4.69
export PATH=${EPICS_INSTALL_DIR}/${EPICS_BASE_NAME}/bin/${EPICS_HOST_ARCH}:$PATH
export EPICS_BASE=${EPICS_INSTALL_DIR}/${EPICS_BASE_NAME}


